"""Added Rent Per Month

Revision ID: 11b2293f2456
Revises: 
Create Date: 2024-10-26 23:39:43.980560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b2293f2456'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rent_per_month', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Properties', schema=None) as batch_op:
        batch_op.drop_column('rent_per_month')

    # ### end Alembic commands ###
