"""Added First and Last name

Revision ID: 53edb733cb79
Revises: 11b2293f2456
Create Date: 2024-10-26 23:49:22.691850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53edb733cb79'
down_revision = '11b2293f2456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
