"""Renamed user table to Users

Revision ID: e75228e80dc5
Revises: c8b347da5a4a
Create Date: 2024-10-30 14:44:16.174644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75228e80dc5'
down_revision = 'c8b347da5a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
